### ISSUE TITLE
Android keyboard overlay. 

### ISSUE THREAD

**Issue by morzyns** [NativeScript/nativescript-angular#1277]
Keyboard overlays the inputs on Android. 
package.json:
```
"nativescript": {
    "id": "org.nativescript.BTrex",
    "tns-android": {
      "version": "4.0.0"
    },
    "tns-ios": {
      "version": "4.0.1"
    }
  },
  "scripts": {
    "lint": "tslint \"app/**/*.ts\""
  },
  "dependencies": {
    "@angular/animations": "~5.2.0",
    "@angular/common": "~5.2.0",
    "@angular/compiler": "~5.2.0",
    "@angular/core": "~5.2.0",
    "@angular/forms": "~5.2.0",
    "@angular/http": "~5.2.0",
    "@angular/platform-browser": "~5.2.0",
    "@angular/platform-browser-dynamic": "~5.2.0",
    "@angular/router": "~5.2.0",
    "ccxt": "^1.12.137",
    "crypto-js": "^3.1.9-1",
    "email-validator": "^1.0.7",
    "nativescript-angular": "^5.3.0",
    "nativescript-async": "^1.0.2",
    "nativescript-iqkeyboardmanager": "^1.1.0",
    "nativescript-nodeify": "^0.7.0",
    "nativescript-numeric-keyboard": "^3.0.3",
    "nativescript-theme-core": "1.0.4",
    "nativescript-ui-listview": "^3.5.4",
    "nativescript-ui-sidedrawer": "^4.0.0",
    "nativescript-webview-interface": "^1.4.2",
    "qs": "^6.5.1",
    "reflect-metadata": "0.1.10",
    "rxjs": "^5.5.5",
    "rxjs-tslint-rules": "^3.14.0",
    "tns-core-modules": "^4.0.0",
    "tns-platform-declarations": "^3.4.1",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~5.2.0",
    "@ngtools/webpack": "~1.9.4",
    "@types/node": "^9.6.4",
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "clean-webpack-plugin": "~0.1.19",
    "codelyzer": "3.2.2",
    "copy-webpack-plugin": "~4.3.0",
    "css-loader": "~0.28.7",
    "extract-text-webpack-plugin": "~3.0.2",
    "lazy": "1.0.11",
    "nativescript-dev-sass": "^1.5.0",
    "nativescript-dev-typescript": "0.7.0",
    "nativescript-dev-webpack": "^0.10.1",
    "nativescript-worker-loader": "~0.8.1",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.2.1",
    "sass-loader": "~6.0.6",
    "tslint": "5.8.0",
    "typescript": "~2.7.2",
    "uglifyjs-webpack-plugin": "~1.1.6",
    "webpack": "~3.10.0",
    "webpack-bundle-analyzer": "^2.9.1",
    "webpack-sources": "~1.1.0"
  }
```
Presentation
```
   <GridLayout *ngIf="!isBuyTabActive" class="market-trade sell" rows="auto, auto, auto, auto, auto, *" columns="*, auto" row="2">
                                    <Label [text]="'Balance Available:'" col="0" row="1"></Label>
                                    <Label *ngIf="balances" [text]="balances['BTC'].BalanceWithCurrency" col="0" row="2" class="balance-label"></Label>
                                    <TextField col="0" hint="Price (BTC)" [(ngModel)]="rateSell" row="3" keyboardType="number" style.placeholderColor="#ccc" class="std-text-field"
                                    autocorrect="false" autocapitalizationType="none"></TextField>
                                    <TextField col="0" hint="Amount" [(ngModel)]="quantitySell" keyboardType="number" (ngModelChange)="onChange($event)" row="4" style.placeholderColor="#ccc" class="std-text-field"
                                    autocorrect="false" autocapitalizationType="none"></TextField>

                                    <Button text="Ask Price" (tap)="populatePriceAsk()" class="btn btn-function" col="1" row="3" borderRadius="2"></Button>
                                    <Button text="Max" (tap)="getMaxSell()" class="btn btn-function" col="1" row="4" borderRadius="2"></Button>
                                    <StackLayout colSpan="2" row="5" class="button-container">
                                        <Button text="Sell" (tap)="proceedTransaction()" class="btn sell-button" borderRadius="2"></Button>
                                    </StackLayout>
                                </GridLayout>
```

![bug](https://user-images.githubusercontent.com/26156929/38733100-03658bee-3f21-11e8-8f7b-18e612aa859d.gif)

I have checked many times removing platforms, upgrading as much as possible. 
tns --version -> 4.0.0-2018-04-05-11377

Really painful bug..

**Comment by tsonevn** [comment]
Hi @morzyns,
You should add the GridLayout container inside a ScrollView. For example:
```
<ScrollView>
<GridLayout *ngIf="!isBuyTabActive" class="market-trade sell" rows="auto, auto, auto, auto, auto, *" columns="*, auto" row="2">
                                    <Label [text]="'Balance Available:'" col="0" row="1"></Label>
                                    <Label *ngIf="balances" [text]="balances['BTC'].BalanceWithCurrency" col="0" row="2" class="balance-label"></Label>
                                    <TextField col="0" hint="Price (BTC)" [(ngModel)]="rateSell" row="3" keyboardType="number" style.placeholderColor="#ccc" class="std-text-field"
                                    autocorrect="false" autocapitalizationType="none"></TextField>
                                    <TextField col="0" hint="Amount" [(ngModel)]="quantitySell" keyboardType="number" (ngModelChange)="onChange($event)" row="4" style.placeholderColor="#ccc" class="std-text-field"
                                    autocorrect="false" autocapitalizationType="none"></TextField>

                                    <Button text="Ask Price" (tap)="populatePriceAsk()" class="btn btn-function" col="1" row="3" borderRadius="2"></Button>
                                    <Button text="Max" (tap)="getMaxSell()" class="btn btn-function" col="1" row="4" borderRadius="2"></Button>
                                    <StackLayout colSpan="2" row="5" class="button-container">
                                        <Button text="Sell" (tap)="processTransaction()" class="btn sell-button" borderRadius="2"></Button>
                                    </StackLayout>
                                </GridLayout>
</ScrollView>
```
This should resolve the overlay issue for Android. For iOS use [nativescript-iqkeyboardmanager](https://www.npmjs.com/package/nativescript-iqkeyboardmanager) plugin.

**Comment by tsonevn** [comment]
Hi @morzyns,
This issue has been fixed with NativeScript 4.0. Can you confirm that you are reproducing the issue with latest NativeScript?

**Comment by morzyns** [comment]
<img width="367" alt="screen shot 2018-04-16 at 1 11 53 pm" src="https://user-images.githubusercontent.com/26156929/38805876-c1e742c6-4177-11e8-9c6e-8c8873d5a775.png">

**Comment by jogboms** [comment]
@morzyns 
Could you add `android:windowSoftInputMode="stateHidden|adjustResize"` to your root activity within `App_Resources`?

**Comment by morzyns** [comment]
Using the latest AndroidManifest.xml with suggested changes
```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
	package="__PACKAGE__"
	android:versionCode="1"
	android:versionName="1.0">

	<supports-screens
		android:smallScreens="true"
		android:normalScreens="true"
		android:largeScreens="true"
		android:xlargeScreens="true"/>

	<uses-sdk
		android:minSdkVersion="17"
		android:targetSdkVersion="__APILEVEL__"/>

	<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
	<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
	<uses-permission android:name="android.permission.INTERNET"/>

	<application
		android:name="com.tns.NativeScriptApplication"
		android:allowBackup="true"
		android:icon="@drawable/icon"
		android:label="@string/app_name"
		android:theme="@style/AppTheme">

		<activity
			android:name="com.tns.NativeScriptActivity"
			android:label="@string/title_activity_kimera"
			android:configChanges="keyboardHidden|orientation|screenSize"
			android:theme="@style/LaunchScreenTheme"
			android:windowSoftInputMode="stateHidden | adjustResize">

			<meta-data android:name="SET_THEME_ON_LAUNCH" android:resource="@style/AppTheme" />

			<intent-filter>
				<action android:name="android.intent.action.MAIN" />
				<category android:name="android.intent.category.LAUNCHER" />
			</intent-filter>
		</activity>
		<activity android:name="com.tns.ErrorReportActivity"/>
	</application>
</manifest>

```
Unfortunately the issue still exists.
Checked after removing platform android and running tns run android --clean

**Comment by tsonevn** [comment]
Hi @morzyns,
I reused some part of the attached code from your previous comment, however, I am unable to recreate the issue with the keyboard overlay. It would help if you could provide a sample project, which could be used for debugging.

**Comment by jogboms** [comment]
@morzyns 
Oh! In that case, i might think it has something to do with
```
ScrollView
    > GridLayout
    > GridLayout
```
How about wrapping both `GridLayout`s with a `StackLayout`
```
ScrollView
    > StackLayout
        > GridLayout
        > GridLayout
```

**Comment by morzyns** [comment]
Hi again @jogboms & @tsonevn.

After checking everything up step by step it came up, the issue is when the navigation.

Issue is when navigating via angular/router

This caused the issue.
`this.router.navigate(['/market', {market: this.markets[$event.index].symbol}]);
`
after changing to RouterExtensions it works good.


Thank you for the help.
@jogboms Btw. i think you're right that ScrollView should have just one child element.

**Comment by tsonevn** [comment]
Hi @morzyns,
We will check this scenario on our side.

**Comment by morzyns** [comment]
Another  use case that caused the bug:
```
<StackLayout visibility="{{ !loading ? 'visible' : 'collapsed' }}" height="100%" width="100%" orientation="vertical" row="0">
        <web-view (loadFinished)="pageLoaded()" height="100%" width="100%" #wView></web-view>
</StackLayout> 
```
While using just 

` <web-view (loadFinished)="pageLoaded()" height="100%" width="100%" #wView></web-view>`
 works fine..
I don't know if it's just element's visibility or webView specific bug.

**Comment by morzyns** [comment]
Another use case that caused the bug:

<StackLayout visibility="{{ !loading ? 'visible' : 'collapsed' }}" height="100%" width="100%" orientation="vertical" row="0">
        <web-view (loadFinished)="pageLoaded()" height="100%" width="100%" #wView></web-view>
</StackLayout> 
While using just

<web-view (loadFinished)="pageLoaded()" height="100%" width="100%" #wView></web-view>
works fine..
I don't know if it's just element's visibility or webView specific bug.

**Comment by jogboms** [comment]
@morzyns I believe i've experienced this one before i think i switched the `StackLayout` to a `GridLayout`

**Comment by morzyns** [comment]
```
<!-- <ios>
    <GridLayout visibility="{{ !loading ? 'visible' : 'collapsed' }}">
        <web-view (loadFinished)="pageLoaded()" height="100%" width="100%" #wView></web-view>
    </GridLayout>
    <ActivityIndicator *ngIf="loading" busy="{{true}}" width="100" height="100"></ActivityIndicator>
</ios>
<android> -->
    <web-view height="100%" width="100%" #wView></web-view>
<!-- </android> -->
```
Can't preload web-view without issues on Android. (Issues with keyboard for instance)

**Comment by morzyns** [comment]
Still unstable as hell. Sometimes works sometimes not.. - depends on page data loading.

Guys, could you feedback on this? 
It's serious bug. I can't event downgrade, - this issue exists and have no clue what's caused it..

For now, after 1,5 month WebView == unstable.

**Comment by kbajjuri** [comment]
Try adding `android:windowSoftInputMode="adjustPan"` to your App_Resources/AndroidManifest.xml <activity>. adjustSize will not work.

**Comment by jibon57** [comment]
@tsonevn any work around for this? Using webview in Android became impossible now.

**Comment by ematechno** [comment]
I have the same issue with **Angular** on **Android**.

The issue can be reproduced easily.

I created the project using "Angular Drawer Navigation Template" from: 
https://github.com/NativeScript/template-drawer-navigation-ng

Then I updated "settings.components.html" as per below:

<GridLayout class="page page-content">
    <ScrollView>
        <StackLayout class="page form p-15">
            <StackLayout class="input-field">                    
                <Label class="label font-weight-bold m-b-5" text="{{'lastname'  }}" textWrap="true"></Label>
                <TextField id="customer-lastname" [(ngModel)]="customer.lastname" class="input"></TextField>
                <Label class="label font-weight-bold m-b-5" text="{{'name'  }}" textWrap="true"></Label>
                <TextField [(ngModel)]="customer.firstname" class="input"></TextField> 
                <Label class="label font-weight-bold m-b-5" text="{{'phone'  }}" textWrap="true"></Label>
                <TextField [(ngModel)]="customer.phone" keyboardType="phone" class="input"></TextField>  
                <Label class="label font-weight-bold m-b-5" text="{{'email'  }}" textWrap="true"></Label>
                <TextField [(ngModel)]="customer.email" keyboardType="email" autocorrect="false" autocapitalizationType="none" class="input"></TextField>
                <Label class="label font-weight-bold m-b-5" text="{{'lastname'  }}" textWrap="true"></Label>
                <TextField id="customer-lastname" [(ngModel)]="customer.lastname" class="input"></TextField>
                <Label class="label font-weight-bold m-b-5" text="{{'name'  }}" textWrap="true"></Label>
                <TextField [(ngModel)]="customer.firstname" class="input"></TextField> 
                <StackLayout class="hr-light"></StackLayout>                                     
                <Label class="label font-weight-bold m-b-5 m-t-20" text="{{'notes'  }}" textWrap="true"></Label>
                <TextView [(ngModel)]="customer.notes" maxLength="130" borderWidth="1" returnKeyType="send" class="input input-border"></TextView>
            </StackLayout>
        </StackLayout>
    </ScrollView>
</GridLayout> 


I tried to update "AndroidManifest.xml" with "android:windowSoftInputMode="adjustResize", but nothing changed!!!

Attach my sample project.



Any suggestion or work-aroud?

**Comment by neil-119** [comment]
Like the above users, I would love to know a solution for this as well.

**Comment by tsonevn** [comment]
Hi all,
I researched the case again and found a possible solution about this scenario. You can try to set up `SOFT_INPUT_ADJUST_RESIZE` flag in the project via code behind on page loaded event and to check whether the view will be displayed above the keyboard. For example:
TypeScript 
```
import { Component, OnInit } from "@angular/core";
import * as app from "application"
import {Page} from "ui/page"
import { Item } from "./item";
import { ItemService } from "./item.service";
declare var android:any;
@Component({
    selector: "ns-items",
    moduleId: module.id,
    templateUrl: "./items.component.html",
})
export class ItemsComponent implements OnInit {
    items: Item[];

    // This pattern makes use of Angular’s dependency injection implementation to inject an instance of the ItemService service into this class. 
    // Angular knows about this service because it is included in your app’s main NgModule, defined in app.module.ts.
    constructor(private itemService: ItemService, private page:Page) { 
        this.page.on("loaded", (args)=>{
            var window = app.android.startActivity.getWindow();
            window.setSoftInputMode(android.view.WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);
        })
    }

    ngOnInit(): void {
        this.items = this.itemService.getItems();
    }
}
```

**Comment by jibon57** [comment]
Thanks for reply @tsonevn but unfortunately it isn't working... 

` <WebView id="webview" src="http://m-dg.oreyw.com/"></WebView>`

```
this.page.on("loaded", (args) => {
            var window = app.android.startActivity.getWindow();
            window.setSoftInputMode(android.view.WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);
        })
```

**Comment by ematechno** [comment]
@tsonevn  - thanks for suggestion but I confirm it doesn't work for me as well.

As suggested on NS community, I tried to set "fitsSystemWindows" to true for "adjustResize" - this works but it has a weird side effect on drawer appearence - all details in below link:

https://discourse.nativescript.org/t/android-keyboard-overlay-tns-4-1-3/6778

**Comment by tsonevn** [comment]
Hi @jibon57,
Make sure that after the changes, you are making a clear project rebuild. Regarding that I would suggest to try the described steps below and to check again if the behaviour will be the same:
1. remove the platform with `tns platform remove android`
2. delete the app from the simulator or device, which you used for debugging
3, rebuild the app with `tns run android`.

For your convenience, I am attaching the sample project and the video, which demonstrates the behaviour on my side after adding the flag via code-behind.
[Archive.zip](https://github.com/NativeScript/nativescript-angular/files/2183085/Archive.zip)
[testvideo.zip](https://github.com/NativeScript/nativescript-angular/files/2183086/testvideo.zip)


@ematechno, if you are facing a problem with the drawer component, please log an issue in the [nativescript-ui-feedback](https://github.com/telerik/nativescript-ui-feedback/issues) repository. While opening the issue, also provide a sample project, which can be used for debugging.

**Comment by jibon57** [comment]
@tsonevn thanks again. I have noticed this problem is happening mainly with `tns-template-drawer-navigation-ng` or `tns-template-tab-navigation-ng`. Blank one seems work well. Please have a look the attached project.

[Archive.zip](https://github.com/NativeScript/nativescript-angular/files/2184010/Archive.zip)

**Comment by ematechno** [comment]
@tsonevn  as suggested, I have just opened a new bug in nativescript-ui-feedback repository

https://github.com/telerik/nativescript-ui-feedback/issues/730

**Comment by tsonevn** [comment]
HI @jibon57,
Thank you for the sample project. I tested it on my side, and this seems to be related to the scenario when the RadSideDrawer is used as a root component. Regarding that, I will suggest leaving your comment in the [issue](https://github.com/telerik/nativescript-ui-feedback/issues/730) logged by @ematechno and attach there your project.

**Comment by kpinzon** [comment]
`window.setSoftInputMode(android.view.WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);`

Is working for me. As well as setting SOFT_INPUT_ADJUST_PAN in code for the page.

I had it set in the manifest as AdjustUnspecified. I noticed that after setting one page to AdjustResize in the page code, as above, it persisted as AdjustResize across the app. Every textfield after hitting the page with the above code would now follow the same keyboard adjust style. I am now setting the keyboard for each page to either AdjustPan or AdjustResize and that seems to work for me. Hopefully this helps someone.

I also had to redo the layout on my page. The AdjustResize was finicky. It would push up bottom navigation if the main grid didn't have a `*` row. With a `*` row it pushes everything above the textfield but not the bottom nav. Setting each row's height also forced bottom nav to show under textfield, it was ugly. So for me, using a grid, I had to play around with rows, even add a whitespace row with a height, etc.. I don't know why, but for my project I got it at a place I'm happy with. But it's still been a pain.

**Comment by NeriCodec** [comment]
+1

**Comment by Manbearpixel** [comment]
Hey all, I appreciate all the input everyone has added here in this issue! I've asked this related question and posted an answer for it which sums up details I've so far read between this issue and a few others like it (and linked back to it as a resource).

I hope the solution I've gathered so far works here and for anyone else! I'd also like to note that I think there *may* be a bug in NativeScript which ends up ignoring the `windowSoftInputMode` property in `AndroidManifest.xml` **if** the application is `suspended` and `resumed` on the same view this issue occurs!

https://stackoverflow.com/questions/53980913/stop-keyboard-overlay-when-interacting-with-textfield-in-a-nativescript-applicat

**Comment by ibnYusrat** [comment]
@Manbearpixel The issue here is mainly with people using the SideDrawer.

**Comment by Manbearpixel** [comment]
@ibnYusrat I use the `RadSideDrawer` in my project and have resolved the keyboard overlay issue.

**Comment by Macarthurval** [comment]
For those who are desperate how I, with this method can easily detect if the keyboard is shown or hidden and also its height:

    if ( app.android ) {
        var prevHeightDiff = 0
        const group = frameModule.topmost().android.rootViewGroup
        group.getViewTreeObserver().addOnGlobalLayoutListener(new android.view.ViewTreeObserver.OnGlobalLayoutListener({
            onGlobalLayout: function() {

                var r = new android.graphics.Rect();
                group.getWindowVisibleDisplayFrame(r);
                var dm = group.getResources().getDisplayMetrics();
                var heightDiff = group.getBottom() - r.bottom;

                if( heightDiff != prevHeightDiff ){
                    prevHeightDiff = heightDiff
                    if( heightDiff ){
                        console.log( "KEYBOARD SHOWN!!!" )
                        console.log( "keyboard height: " + heightDiff )
                    }else{
                        console.log( "KEYBOARD HIDDEN!!!" )
                    }
                }
            }
        }))
    }

This works without any additional configuration even with sidedrawer.

**Comment by Macarthurval** [comment]
Just found the perfect solution that works for me!, in `AndroidManifest.xml` in `application` tag, add the property `android:windowSoftInputMode="adjustResize"`, and inside the page when you have the webview add a on page `loaded` event:

    exports.onLoaded = function( args ){
        if ( args.object.android ) {
            args.object.android.setFitsSystemWindows(true);
        }
    }

Working perfect with SideDrawer and webview.

**Comment by oluwaseye** [comment]
I fixed mine by adding the 
`android:windowSoftInputMode="stateAlwaysHidden|adjustResize"` to the activity tag in the `AndroidManifest.xml`

and updating the `/vaules/styles.xml` by adding a new item tag
` <item name="android:fitsSystemWindows">true</item>`

This also helped with device notch issue by fitting the app in the device

**Comment by zhiyong80** [comment]
@oluwaseye could you specify where to add entries into both xml files? I am having the same issues, so far everything else seems not working. Weird thing is if install app through tns preview, keypad seems to be located perfectly fine.

**Comment by oluwaseye** [comment]
@zhiyong80 
I added mine within the LaunchScreenThemeBase Style
 `<style name="LaunchScreenThemeBase" parent="Theme.AppCompat.Light.NoActionBar">`
`<item name="android:fitsSystemWindows">true</item>`

Just in one xml file, the App_Resources/Android/src/main/res/values/styles.xml

**Comment by rommyarb** [comment]
After adding `android:windowSoftInputMode="stateHidden|adjustResize"` to main <activity> in _/YourProject/app/App_Resources/Android/src/main/AndroidManifest.xml_ , don't forget to remove the `platforms` directory. Finally, build and run it again

**Comment by rommyarb** [comment]
After adding `android:windowSoftInputMode="stateHidden|adjustResize"` to the main activity in _/YourProject/app/App_Resources/Android/src/main/AndroidManifest.xml_ , don't forget to remove the `platforms` directory. Finally, build and run it again.

**Comment by valera1401** [comment]
Hi all. 
Thank you for your suggestions. 
I've tried everything but unfortunately nothing helped.  
'adjustPan' is working but it moves the Action Bar out of the screen.
stateAlwaysHidden|adjustResize + android:fitsSystemWindows is working as well but in this case Action Bar looks ugly as described here https://github.com/NativeScript/nativescript-ui-feedback/issues/730#issuecomment-408487871

My application has the Side drawer.  And keyboard overlaps text fields only when ScrollView is the root component of the page.

**Comment by lano-vargas** [comment]
I'm experiencing this issue with `ModalDialogService` `from '@nativescript/angular'` when is in a modal popup with a form the an input is focus at the bottom of the page the keyboard cover all the inputs to the height of the keyboard and does not push the elements up even with the Scrollview element.
