### ISSUE TITLE
Error: Css styling failed: ReferenceError: Can't find variable: __spreadArrays

### ISSUE THREAD

**Issue by marklanhamhc** [NativeScript/nativescript-angular#1983]
When I run **tns run ios** or **tns run android** I get the following error in Terminal on my MacBook Pro:

**CONSOLE ERROR file:///node_modules/tns-core-modules/trace/trace.js:174:0: Error: Css styling failed: ReferenceError: Can't find variable: __spreadArrays**

**tns doctor**:
No issues were detected.
✔ Your ANDROID_HOME environment variable is set and points to correct directory.
✔ Your adb from the Android SDK is correctly installed.
✔ The Android SDK is installed.
✔ A compatible Android SDK for compilation is found.
✔ Javac is installed and is configured properly.
✔ The Java Development Kit (JDK) is installed and is configured properly.
✔ Xcode is installed and is configured properly.
✔ xcodeproj is installed and is configured properly.
✔ CocoaPods are installed.
✔ CocoaPods update is not required.
✔ CocoaPods are configured properly.
✔ Your current CocoaPods version is newer than 1.0.0.
✔ Python installed and configured correctly.
✔ The Python 'six' package is found.
✔ Xcode version 10.3.0 satisfies minimum required version 10.
✔ Getting NativeScript components versions information...
✔ Component nativescript has 6.1.0 version and is up to date.
✔ Component tns-core-modules has 6.1.1 version and is up to date.
✔ Component tns-android has 6.1.0 version and is up to date.
✔ Component tns-ios has 6.1.0 version and is up to date.

Package:
```{
  "nativescript": {
    "id": "com.myapp.MyApp",
    "tns-ios": {
      "version": "6.1.0"
    },
    "tns-android": {
      "version": "6.1.0"
    }
  },
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "repository": "<fill-your-repository-here>",
  "scripts": {
    "lint": "tslint \"app/**/*.ts\""
  },
  "dependencies": {
    "@angular/animations": "~8.2.6",
    "@angular/common": "~8.2.6",
    "@angular/compiler": "~8.2.6",
    "@angular/core": "~8.2.6",
    "@angular/forms": "~8.2.6",
    "@angular/http": "~7.2.15",
    "@angular/platform-browser": "~8.2.6",
    "@angular/platform-browser-dynamic": "~8.2.6",
    "@angular/router": "~8.2.6",
    "@types/node": "^12.7.5",
    "html-encoder-decoder": "^1.3.8",
    "jwt-decode": "^2.2.0",
    "nativescript-advanced-webview": "^4.0.1",
    "nativescript-angular": "^8.2.1",
    "nativescript-appversion": "^1.4.2",
    "nativescript-email": "^1.5.5",
    "nativescript-https": "^1.1.0",
    "nativescript-iqkeyboardmanager": "^1.5.1",
    "nativescript-ngx-fonticon": "^4.2.1",
    "nativescript-plugin-firebase": "^9.1.1",
    "@nstudio/nativescript-pulltorefresh": "^1.0.1",
    "nativescript-root-detection": "^1.0.0",
    "nativescript-secure-storage": "^2.5.0",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-ui-gauge": "^5.0.0",
    "reflect-metadata": "~0.1.13",
    "rxjs": "^6.5.3",
    "rxjs-compat": "^6.5.3",
    "snyk": "^1.227.0",
    "tns-core-modules": "6.1.1",
    "webpack": "^4.40.2",
    "zone.js": "^0.10.2"
  },
  "devDependencies": {
    "@angular/compiler-cli": "8.2.0",
    "@ngtools/webpack": "8.2.0",
    "codelyzer": "~5.1.0",
    "nativescript-dev-webpack": "^1.2.0",
    "node-sass": "4.12.0",
    "tns-platform-declarations": "^6.1.1",
    "tslint": "~5.20.0",
    "typescript": "~3.5.3",
    "webpack-obfuscator": "^0.18.3"
  },
  "readme": "NativeScript Application"
}
```
 
**Describe the bug**
Both iOS and Android emulators fire up with either an unstyled app (iOS) or a blank screen (Android) after upgrading to NS6.

**To Reproduce**
Just run **tns run ios** or **tns run android**

**Expected behavior**
Should boot up the app login screen

**Sample project**
This is a private app.

**Comment by marklanhamhc** [comment]
Thanks to @tsonevn, I managed to resolve this issue by doing the following:

01. Delete the follow files/folders:
- node_modules
- platforms
- hooks
- package-lock.json
- webpack.config.js

02. Run: **npm i**

03. Then just rebuild the project: **tns run <platform_name>**

This should resolve the issue.

**Comment by romandragan** [comment]
Was able to resolve it with @marklanhamhc's workaround from here: https://github.com/NativeScript/nativescript-dev-webpack/issues/1037#issue-489216505

**Comment by razorsyntax** [comment]
This didn't resolve the issue for me.  I'm stilling getting the error after deleting the folders/files and running `tns run ios`.  I'm running `tns-ios: 6.1.1` in my package json.
